### ISSUE TITLE
Enable offline access

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-workflow#47]
We would like users to have offline access to Electric Book sites. Perhaps offline access to the Electric Book Manager, too. What tools and approaches might we use for that?

**Comment by arthurattwell** [comment]
@SteveBarnett suggests investigating service workers:

> There are loads of examples / recipes out there that we can use. https://serviceworke.rs/ has a bunch.
> 
> And there are snippets for using Jekyll to generate the serviceworker and to bust the cache ([three bookmarks on the topic](https://pinboard.in/u:maxbarners/t:jekyll/t:serviceworker/)).
> 
> This feels like a small bit of work that could be widely useful: [support is rolling out for it in newer Androids](http://caniuse.com/#feat=serviceworkers), even lower spec ones.

**Comment by antoinentl** [comment]
A great example for an offline first web book: [Resilient Web Design](https://resilientwebdesign.com/) by Jeremy Keith, with a limit: the amount of data which stored locally ([an article about that](https://nicolas-hoizey.com/2017/01/how-much-data-should-my-service-worker-put-upfront-in-the-offline-cache.html)).

An interesting approach: suggest this option to the users. An article about that: [Implementing "Save For Offline" with Service Workers](http://una.im/save-offline/).

**Comment by arthurattwell** [comment]
This issue was moved to electricbookworks/electric-book#154
