### ISSUE TITLE
Add guidance/support for translations

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-workflow#8]
This post describes a good way to manage translations:

https://developmentseed.org/blog/multilingual-jekyll-sites/

**Comment by julianorrish** [comment]
Awesome! You'll probably have to explain this to me a little, but if I
understand then its pretty cool.

**Comment by arthurattwell** [comment]
A passing note: the [Polyglot plugin](https://github.com/untra/polyglot) looks interesting, but I don't like the idea of messing with Jekyll at this depth.

**Comment by arthurattwell** [comment]
The setup in https://github.com/bookdash/bookdash-books is working well there.

**Comment by arthurattwell** [comment]
Fixed in #50.
